fq_dir:  '/data/mcgaugheyd/projects/nei/bharti/zander_bharti_iRPE_differentiation/fastq'
run_recount_pump: '/home/mcgaugheyd/git/monorail-external/singularity/run_recount_pump.sh'
run_recount_unify: '/home/mcgaugheyd/git/monorail-external/singularity/run_recount_unify.sh'
genome:  'hg38'
project:  'zander'
recount_ref:  '/data/mcgaugheyd/genomes/hg38_monorail/'
pump_sif:  '/data/mcgaugheyd/genomes/hg38_monorail/recount-rs5_1.0.6.sif'
unify_sif: '/data/mcgaugheyd/genomes/hg38_monorail/recount-unify_1.1.0.sif'
fq1_suffix:  '_R1_001.fastq.gz'
fq2_suffix:  '_R2_001.fastq.gz'
cores:  6
study_fq: 'study_fq.tsv'
working_dir: '/data/mcgaugheyd/projects/nei/bharti/zander_bharti_iRPE_differentiation/'
organism: 'human'
